---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisapp
  namespace: realtime
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
      namespace: realtime
    spec:
      containers:
      - name: redis
        image: redis:4-32bit
        resources:
          requests:
            cpu: 200m
            memory: 100Mi
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redisapp
  namespace: realtime
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: realtimeapp
  namespace: realtime
  labels:
    app: realtimeapp
spec:
  selector:
    matchLabels:
      app: realtimeapp
  replicas: 2
  template:
    metadata:
      labels:
        app: realtimeapp
      namespace: realtime
    spec:
      containers:
      - name: realtimeapp
        image: gbaeke/realtime-go
        env:
        - name: REDISHOST
          value: "redisapp:6379"
        resources:
          requests:
            cpu: 25m
            memory: 50Mi
          limits:
            cpu: 150m
            memory: 150Mi
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: realtimeapp
  namespace: realtime
  labels:
    app: realtimeapp
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8888
  selector:
    app: realtimeapp